### ISSUE TITLE
Executors dies silently

### ISSUE THREAD

**Issue by vegahar** [yaronr/docker-mesos#4]
Have you solved the issue with executors silently dying? I have the same issue with the mesosphere tutorial. UI and uploading topologies works fine.

Whenever using the wurstmeister/storm project everything works fine

**Comment by yaronr** [comment]
Hi @vegahar 

To be frank, I have turned my focus in other directions recently.
All in all, this is a very small amount of 'code' - so it should be relatively simple to fix this issue.

If you provide a fix, I would gladly accept your pull request.
